# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f29a6a1ba00d2db86f69e0559c230dd1"
name = "ost"
application_url = "https://information-morgan-root-profit.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_shipping,write_shipping"

[auth]
redirect_urls = ["https://information-morgan-root-profit.trycloudflare.com/auth/callback", "https://information-morgan-root-profit.trycloudflare.com/auth/shopify/callback", "https://information-morgan-root-profit.trycloudflare.com/api/auth/callback"]
